const Constants = {
    USER_LOGGEDIN: 'USER_LOGGEDIN',
    USER_LOGOUT: 'USER_LOGOUT',
    FETCH_PRODUCTS: 'FETCH_PRODUCTS',
    FETCH_PRODUCT: 'FETCH_PRODUCT',
    SET_PRODUCT: 'SET_PRODUCT',
    POST_REVIEW: 'POST_REVIEW',
    PURCHASE_POSTED:'PURCHASE_POSTED',
    PURCHASE_RESET:'PURCHASE_RESET'
}

export default Constants;